<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <IsPackable>false</IsPackable>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="Xunit.StaFact" Version="1.1.11" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="DocDr.TestSupport" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DocDr.App\DocDr.App.csproj" />
    <ProjectReference Include="..\..\src\DocDr.Pdf\DocDr.Pdf.csproj" />
    <ProjectReference Include="..\DocDr.TestSupport\DocDr.TestSupport.csproj" />
  </ItemGroup>

</Project>
