<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>DocDr.App</RootNamespace>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\DocDr.ico</ApplicationIcon>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\DocDr.ico" />
    <Resource Include="Assets\DocDr.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DocDr.Pdf\DocDr.Pdf.csproj" />
    <ProjectReference Include="..\DocDr.Ocr\DocDr.Ocr.csproj" />
  </ItemGroup>

</Project>
